// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdBBleD3RALVbVdGg9mRM-afDYDRD8v8U',
    appId: '1:159962363590:web:f529b782fe165cf24589c7',
    messagingSenderId: '159962363590',
    projectId: 'whereiscorral',
    authDomain: 'whereiscorral.firebaseapp.com',
    storageBucket: 'whereiscorral.appspot.com',
    measurementId: 'G-YGQSJNH45K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9wwbtK_Bo88IGobxalhSsDr8LUPlALn0',
    appId: '1:159962363590:android:085597cc799b87b74589c7',
    messagingSenderId: '159962363590',
    projectId: 'whereiscorral',
    storageBucket: 'whereiscorral.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_5B8aVuyC7m4CFhJryH5_KpVFqFScrsU',
    appId: '1:159962363590:ios:288cb4dfbb3fcf384589c7',
    messagingSenderId: '159962363590',
    projectId: 'whereiscorral',
    storageBucket: 'whereiscorral.appspot.com',
    iosClientId: '159962363590-3utcjtmnq1jr5s2iplogv28pnk4ul6m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.whereiscorral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_5B8aVuyC7m4CFhJryH5_KpVFqFScrsU',
    appId: '1:159962363590:ios:288cb4dfbb3fcf384589c7',
    messagingSenderId: '159962363590',
    projectId: 'whereiscorral',
    storageBucket: 'whereiscorral.appspot.com',
    iosClientId: '159962363590-3utcjtmnq1jr5s2iplogv28pnk4ul6m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.whereiscorral',
  );
}
